import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './components/sidebar'
import {info} from "./data/data"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
    <body className='flex flex-col sm:flex-row'>
        <Sidebar info={info} />
        <main className='grow-full p-8 sm:p-16 w-full sm:basis-3/4  ml-auto'>
          {children}
        </main>
    </body>
  </html>
  )
}
